toggle_invitees:
  type: bool
  default: true
  description:
    en: "Show/Hide Attending Invited Users"
max_events:
  type: integer
  default: 3
  min: 1
  max: 10
  description:
    en: "Set the maximum number of events to appear in the layout"
