toggle_invitees:
  type: enum
  choices:
    - "Disabled"
    - "Show on Hover"
    - "Always Show"
  default: "Show on Hover"
  description:
    en: "Select if/how invitees will appear in the layout."
max_events:
  type: integer
  default: 3
  min: 1
  max: 10
  description:
    en: "Set the maximum number of events to appear in the layout"
highlight_today:
  type: bool
  default: true
  description:
    en: "Highlight events occuring on the same today"
style:
  type: enum
  choices:
    - "Default"
    - "Comfortable"
    - "Compact"
  default: "Default"
  description:
    en: "Select the layout's view style"
theme:
  type: enum
  choices:
    - "Default"
    - "Modern"
    - "Minimal"
  default: "Default"
  description:
    en: "Select the layout's theme style"
svg_icons:
  default: "calendar|check|star|times|question"
  type: "list"
  list_type: "compact"
  description:
    en: "The required SVG icons the widget needs to display"
